name: Build WPF App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build Solution
      run: msbuild CyberSecurity_ChatBot/CyberSecurity_ChatBot.sln /t:Restore,Build /p:Configuration=Release

    - name: Display Success Message
      run: echo Build completed successfully!
